### ISSUE TITLE
Known Limitations?

### ISSUE THREAD

**Issue by KoenLav** [radekmie/changestream-to-redis#1]
Are the Known Limitations from oplogtoredis also there in this package, or not?

https://github.com/tulip/oplogtoredis#known-limitations

**Comment by radekmie** [comment]
Both of those are limitations of `cultofcoders:redis-oplog` using `externalRedisPublisher`, not `changestream-to-redis` (or `oplogtoredis`), so yes, they still apply.

I believe it'd be easy to fix it, though. Right now this flag simply blocks all outgoing requests (https://github.com/cult-of-coders/redis-oplog/blob/58ba4266f4978f061081c641efe89ce9db9b791b/lib/mongo/lib/dispatchers.js#L29), but instead should check if it's a namespaced or synthetic one.

**Comment by KoenLav** [comment]
Ah, that's clear thanks!

Our collections already have a _tenantId field which is used for all find operations. Would it even make sense to add a namespace to queries then, as the subscription would already filter based on _tenantId in the document/selector?

**Comment by radekmie** [comment]
Based on the docs it would help, but I never used it, so it's hard for me to tell how much (in terms of CPU or RAM). We do the same at aleno (i.e., use a tenant ID field) without custom namespaces and it works just fine.
